export const GET_MERCHANTS = 'GET_MERCHANTS';
export const SET_MERCHANTS = 'SET_MERCHANTS';
export const SET_SELECTED_MERCHANT = 'SET_SELECTED_MERCHANT';
export const SET_TABLE_NUMBER = 'SET_TABLE_NUMBER';